name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install tfsec
        uses: jaxxstorm/action-install-gh-release@release/v1.2.0
        with:
          repo: aquasecurity/tfsec
          tag: v0.58.9
      - name: set python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: code-quality
        run: make code-quality
