name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      ENV: demo
    steps:
      - uses: actions/checkout@v2
      - name: setup gcp
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{secrets.GCLOUD_PROJECT_ID}}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          export_default_credentials: true
      - name: set terraform version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6       -
      - name: setup terraform backend
        run: |
          echo "bucket = \"${{secrets.TF_STATE_BUCKET}}\"" > ./terraform/env/${ENV}/terraform.backend
          echo "prefix = \"${{secrets.TF_STATE_PREFIX}}\"" >> ./terraform/env/${ENV}/terraform.backend
      - name: set python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: install tfsec
        run: brew install tfsec
      - name: code-quality
        run: make code-quality
      - name: terraform plan
        run: make env=${ENV} plan
      - uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: ./terraform/deploy/terraform.tfplan
      - uses: actions/upload-artifact@v2
        with:
          name: app-zip
          path: ./terraform/deploy/generated/app.zip

  apply:
    needs:
      - plan
    runs-on: ubuntu-latest
    env:
      ENV: demo
    environment: shows-api-demo
    steps:
      - uses: actions/checkout@v2
      - name: setup gcp
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{secrets.GCLOUD_PROJECT_ID}}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          export_default_credentials: true
      - name: set terraform version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6       -
      - name: setup terraform backend
        run: |
          echo "bucket = \"${{secrets.TF_STATE_BUCKET}}\"" > ./terraform/env/${ENV}/terraform.backend
          echo "prefix = \"${{secrets.TF_STATE_PREFIX}}\"" >> ./terraform/env/${ENV}/terraform.backend
      - uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: ./terraform/deploy/terraform.tfplan
      - uses: actions/upload-artifact@v2
        with:
          name: app-zip
          path: ./terraform/deploy/generated/app.zip
      - name: terraform apply
        run: make env=${ENV} apply
