name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    env:
      ENV: demo
    steps:
      - uses: actions/checkout@v2
      - name: set python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: install tfsec
        run: brew install tfsec
      - name: code-quality
        run: make code-quality
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      - name: setup terraform backend
        run: |
          echo "bucket = \"${{secrets.TF_STATE_BUCKET}}\"" > ./terraform/env/${ENV}/terraform.backend
          echo "prefix = \"${{secrets.TF_STATE_PREFIX}}\"" >> ./terraform/env/${ENV}/terraform.backend
      - name: terraform plan
        run: make env=${ENV} plan
